# Generated by Django 3.2.5 on 2021-08-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('task_date', models.DateField()),
                ('task_time', models.TimeField()),
                ('task_des', models.TextField()),
                ('work_done', models.TextField()),
            ],
        ),
    ]
